/*===-- mlir/Support/ABINamespaceTag.h - MLIR ABI namespace tag --*- C -*-===*\
|*                                                                            *|
|* Part of the LLVM Project, under the Apache License v2.0 with LLVM          *|
|* Exceptions.                                                                *|
|* See https://llvm.org/LICENSE.txt for license information.                  *|
|* SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception                    *|
|*                                                                            *|
|*===----------------------------------------------------------------------===*|
|*                                                                            *|
|* Generated by CMake from ABINamespaceTag.h.cmake. Do not edit directly.     *|
|*                                                                            *|
|* Exposes the build's MLIR ABI namespace tag:                                *|
|*                                                                            *|
|*   MLIR_ABI_NAMESPACE           - identifier token. Defined only when       *|
|*                                  tagging is active.                        *|
|*   MLIR_ABI_NAMESPACE_ACTIVE    - defined (as 1) iff the tag is non-empty.  *|
|*                                                                            *|
\*===----------------------------------------------------------------------===*/

#ifndef MLIR_SUPPORT_ABINAMESPACETAG_H
#define MLIR_SUPPORT_ABINAMESPACETAG_H

#cmakedefine MLIR_ABI_NAMESPACE @MLIR_ABI_NAMESPACE@

#cmakedefine MLIR_ABI_NAMESPACE_ACTIVE @MLIR_ABI_NAMESPACE_ACTIVE@

#endif
