//===-- WaveAMDOps.td - WaveAMD Python bindings entry -----*- tablegen -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef PYTHON_BINDINGS_WAVEAMD_OPS
#define PYTHON_BINDINGS_WAVEAMD_OPS

include "mlir/Dialect/Wave/IR/WaveAMDOps.td"

#endif
