/*===-- llvm/Support/ABINamespaceTag.h - ABI namespace tag --------*- C -*-===*\
|*                                                                            *|
|* Part of the LLVM Project, under the Apache License v2.0 with LLVM          *|
|* Exceptions.                                                                *|
|* See https://llvm.org/LICENSE.txt for license information.                  *|
|* SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception                    *|
|*                                                                            *|
|*===----------------------------------------------------------------------===*|
|*                                                                            *|
|* Generated by CMake from ABINamespaceTag.h.cmake. Do not edit directly.     *|
|*                                                                            *|
|* Exposes the build's ABI namespace tag to C and C++ code:                   *|
|*                                                                            *|
|*   LLVM_ABI_NAMESPACE           - identifier token (e.g. v23_0). Defined    *|
|*                                  only when tagging is active.              *|
|*   LLVM_ABI_NAMESPACE_ACTIVE    - defined (as 1) iff the tag is non-empty.  *|
|*                                                                            *|
|* Never gate on `#ifdef LLVM_ABI_NAMESPACE` directly: an accidental empty    *|
|* definition would be true for `#ifdef` while expanding to nothing, yielding *|
|* `inline namespace {` (anonymous) which breaks ODR across TUs.              *|
|*                                                                            *|
\*===----------------------------------------------------------------------===*/

#ifndef LLVM_SUPPORT_ABINAMESPACETAG_H
#define LLVM_SUPPORT_ABINAMESPACETAG_H

#cmakedefine LLVM_ABI_NAMESPACE @LLVM_ABI_NAMESPACE@

#cmakedefine LLVM_ABI_NAMESPACE_ACTIVE @LLVM_ABI_NAMESPACE_ACTIVE@

#endif
